import Footer from './Components/Footer'
import NavBar from './Components/NavBar'
import RouteNames from './Components/RouteNames'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LUMOS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar />
      <RouteNames />
      {children}
      <Footer />
      </body>
    </html>
  )
}
